spring:
  application:
    name: feedme
    admin:
      enabled: false
  jmx:
    enabled: false
  main:
    application-class: com.todoslave.FeedmeApplication

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-name: Naver
            redirect-uri: https://i11b104.p.ssafy.io/api/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-name: Kakao
            client-authentication-method: client_secret_post
            redirect-uri: https://i11b104.p.ssafy.io/api/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id

  datasource:
    url: jdbc:mysql://i11b104.p.ssafy.io:3306/feedme
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      host: localhost
      port: 27017
      database: feedme
      uri: mongodb://localhost:27017/feedme
      
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

redis:
  host: redis  # Redis 컨테이너에 연결
  port: 6379

jwt:
  issuer: todoslave@ssafy.com
  secret_key: ${JWT_SECRET_KEY}
